# Generated by Django 3.1.3 on 2020-11-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201130_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desciirption',
            new_name='description',
        ),
    ]
