# Generated by Django 3.1.3 on 2020-11-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201130_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('out of delivery', 'out of delivery')], max_length=101, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], max_length=200, null=True),
        ),
    ]
